### ISSUE TITLE
DJI M300 Mobile SDK questions

### ISSUE THREAD

**Issue by Shivam-Kataria** [The1only/rosettadrone#135]
I am not sure if this is the right place to ask this question since I am not sure if this is possible with rosettadrone.

But, basically, I have a M300 drone, with the CSM radar attached on top of it, and an Onboard computer. I want to be able to read and analyze the raw data from the CSM radar however, DJI does not allow OSDK to do that, while Mobile SDK can. And MSDK can communicate with the OSDK and send its data. 

What DJI Dev support said was "The onboard device is not able to read the millimeter-wave radar data directly, it has to use the MSDK interface to get the radar data calculated by the flight controller. However, the OSDK and MSDK can communicate with each other, so if the MSDK gets the data you want, you can transmit it to the OSDK."

I want to know if its possible to do something similar with rosetta drone to eliminate the need for the mobile sdk, where I can somehow read the raw CSM radar data from the drone and transmit it to an onboard computer using dji's remote controller for further processing.

**Comment by The1only** [comment]
Rosettadrone is based on the MSDK, and Yes it can talk with the OSDK, however the functions to do what you whant does not exist in Rosettadrone. I did some testing with OSDK to MSDK (sending text messages) but I not sure if this is still there. You will have to add this functionality. The banwith for the MSDK to OSDK and reverse is somewhat limited.  Mostly for commands and text etc. but I might be wrong.Technically all you whant is posible, with some additional coding. Best regardTerje Nilsen9Tek ASNorwayOn 22 Mar 2023, at 21:15, Shivam Kataria ***@***.***> wrote:﻿
I am not sure if this is the right place to ask this question since I am not sure if this is possible with rosettadrone.
But, basically, I have a M300 drone, with the CSM radar attached on top of it, and an Onboard computer. I want to be able to read and analyze the raw data from the CSM radar however, DJI does not allow OSDK to do that, while Mobile SDK can. And MSDK can communicate with the OSDK and send its data.
What DJI Dev support said was "The onboard device is not able to read the millimeter-wave radar data directly, it has to use the MSDK interface to get the radar data calculated by the flight controller. However, the OSDK and MSDK can communicate with each other, so if the MSDK gets the data you want, you can transmit it to the OSDK."
I want to know if its possible to do something similar with rosetta drone to eliminate the need for the mobile sdk, where I can somehow read the raw CSM radar data from the drone and transmit it to an onboard computer using dji's remote controller for further processing.
