### ISSUE TITLE
Dependency problem WebRTC and mapbox

### ISSUE THREAD

**Issue by yblei** [The1only/rosettadrone#221]
### Describe the bug

Hello, 
thanks for the great project!
Buildin the app unfortunately results in the bug, shown above.
Any idea how to fix it?
Greeting!

### Steps To Reproduce

1. Clone Repository
2. Adjust jdk versions
3. Hit "Build Project"

### Screenshots

![image](https://github.com/user-attachments/assets/cc6f2109-3aaf-4ec1-a444-0ae12cc9de51)

### Drone Model

```Markdown
DJI Air 3
```

### Smartphone Model

```Markdown
- Model: emulator
- Android version:
```

**Comment by kripper** [comment]
@angel-ayala can you please take a look?

**Comment by angel-ayala** [comment]
I actually didn't test it in a emulator, but I don't know how the UI could be related. Additionally, the error says that no package was found in any repo. I have the exact gradle config from [master](https://github.com/RosettaDrone/rosettadrone/blob/master/app/build.gradle) if no diff could be a connection issue, maybe?

> Adjust jdk versions

Just to be sure @utn-blei, the adjustement were those in #172 right? which OS are you using?

**Comment by kripper** [comment]
RD only works on specific architectures, because it depends on the DJI SDK.

**Comment by yblei** [comment]
Thanks for the quick reply!

Here is my workflow: 
- git clone the project
- import the project to android studio
- change the versions like in #172  
- waiting for the sync to happen
-> I already obtain warnings about missing dependencies (see screenshot)

- I then try to build -> this leeds to the error seen above

To the best of my knowledge, the probelm should not be related to the emulator. Right?

![image](https://github.com/user-attachments/assets/9d7df6dd-b9cc-4f68-a8b6-89332c46e185)

**Comment by angel-ayala** [comment]
there are a [few post](https://stackoverflow.com/questions/47435348/dji-mobile-sdk-android-studio-emulator-sdk-registration-failed) indicating the emulator thing

**Comment by yblei** [comment]
Thanks :) I cant even generate any .apk though since it fails much earlier in the process.
I can therefore also not test on my mobile device.

How would you recommend building the project?

**Comment by yblei** [comment]
Seems like others face the same issue - at least regarding mapbox:
https://github.com/RosettaDrone/rosettadrone/issues/172#issuecomment-2295017779

In case anyone runs into the same issue: 

Creating an API token and adding it to the build as described below fixed the mapbox problem.
https://stackoverflow.com/questions/68934036/could-not-find-com-mapbox-mapboxsdkmapbox-android-accounts0-7-0-on-fresh-inst

**Comment by HEEJUN-SHIN** [comment]
hello, @utn-blei. I faced the same problem regarding the mapbox and webrtc-google.

Does the https://stackoverflow.com/questions/68934036/could-not-find-com-mapbox-mapboxsdkmapbox-android-accounts0-7-0-on-fresh-inst help the mapbox problem? Should I put the API key inside the password?

I found out the problem comes from 'com.dji:dji-uxsdk:4.16', so I temporally added 
exclude group: 'com.mapbox.mapboxsdk', module: 'mapbox-android-accounts'
below the implementation and It could be built successfully.

**Comment by HEEJUN-SHIN** [comment]
Also, the "Could not find org.webrtc:google-webrtc:1.0.32006" error, it seems like there are no actual file in the maven repository. 

so I tried to look for webrtc-sdk in google repository, and found 
https://github.com/webrtc-sdk/android

using implementation 'io.github.webrtc-sdk:android:125.6422.05'
instead of implementation 'org.webrtc:google-webrtc:1.0.32006' seems resolving the issue.

But I think there should be more changes on the settings.

**Comment by ybleioldaccount** [comment]
Yes, adding the mapbox token resolved the issues. 
I followed the official guid on webboxes wesite though. 

Regarding webrtc: I picked an earlier commit before it was integrated to build the app.

**Comment by ybleioldaccount** [comment]
> Also, the "Could not find org.webrtc:google-webrtc:1.0.32006" error, it seems like there are no actual file in the maven repository.
> 
> so I tried to look for webrtc-sdk in google repository, and found https://github.com/webrtc-sdk/android
> 
> using implementation 'io.github.webrtc-sdk:android:125.6422.05' instead of implementation 'org.webrtc:google-webrtc:1.0.32006' seems resolving the issue.
> 
> But I think there should be more changes on the settings.

Great!! Thanks for sharing.

**Comment by kripper** [comment]
Please provide a pull request. Thanks.
